// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwiC94FQYFSPN2mv-Ff7F77rlJbzx3TaA',
    appId: '1:551002011220:web:3d3d419741fab9218d9fc1',
    messagingSenderId: '551002011220',
    projectId: 'aichat-2ebda',
    authDomain: 'aichat-2ebda.firebaseapp.com',
    storageBucket: 'aichat-2ebda.appspot.com',
    measurementId: 'G-HTQ7KG3ZVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3WKxPt5AwAi-NYe-3QhZ3lARDaW7oWMA',
    appId: '1:551002011220:android:618e66ac31023a3f8d9fc1',
    messagingSenderId: '551002011220',
    projectId: 'aichat-2ebda',
    storageBucket: 'aichat-2ebda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRrz2HQg5jKHcQoRUx74ulOCFHvJaDa6k',
    appId: '1:551002011220:ios:d9830b5dbd3303868d9fc1',
    messagingSenderId: '551002011220',
    projectId: 'aichat-2ebda',
    storageBucket: 'aichat-2ebda.appspot.com',
    iosBundleId: 'com.example.aiChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRrz2HQg5jKHcQoRUx74ulOCFHvJaDa6k',
    appId: '1:551002011220:ios:d9830b5dbd3303868d9fc1',
    messagingSenderId: '551002011220',
    projectId: 'aichat-2ebda',
    storageBucket: 'aichat-2ebda.appspot.com',
    iosBundleId: 'com.example.aiChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwiC94FQYFSPN2mv-Ff7F77rlJbzx3TaA',
    appId: '1:551002011220:web:e871da5c7e274e4c8d9fc1',
    messagingSenderId: '551002011220',
    projectId: 'aichat-2ebda',
    authDomain: 'aichat-2ebda.firebaseapp.com',
    storageBucket: 'aichat-2ebda.appspot.com',
    measurementId: 'G-TX5YG8M0RK',
  );
}
